#spring.datasource.url=jdbc:postgresql://localhost:5432/fincore
#spring.datasource.username=postgres
#spring.datasource.password=Charu@yushi

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080




spring.data.redis.host=${SPRING_REDIS_HOST}
spring.data.redis.port=${SPRING_REDIS_PORT}
spring.data.redis.password=${SPRING_REDIS_PASSWORD}


# expose actuator endpoints
management.endpoints.web.exposure.include=health,info,prometheus

# show details in health (optional but good)
management.endpoint.health.show-details=always