name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Give permission to mvnw
        working-directory: fincore
        run: chmod +x mvnw

      - name: Build with Maven
        working-directory: fincore
        run: ./mvnw clean install
